<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.api.testcases.WeatherInfoServiceTests" tests="7" time="9.102" ignored="0" failures="1" timestamp="05 Oct 2018 16:28:53 GMT" skipped="0" hostname="BNG997C5M2" errors="0">
  <testcase name="InfoService" time="0.880" classname="com.test.api.testcases.WeatherInfoServiceTests"/>
  <testcase name="InfoService" time="0.420" classname="com.test.api.testcases.WeatherInfoServiceTests">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.test.api.testcases.WeatherInfoServiceTests.InfoService(WeatherInfoServiceTests.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- InfoService -->
  <testcase name="InfoService" time="1.065" classname="com.test.api.testcases.WeatherInfoServiceTests"/>
  <testcase name="InfoService" time="1.194" classname="com.test.api.testcases.WeatherInfoServiceTests"/>
  <testcase name="InfoService" time="0.894" classname="com.test.api.testcases.WeatherInfoServiceTests"/>
  <testcase name="InfoService" time="1.395" classname="com.test.api.testcases.WeatherInfoServiceTests"/>
  <testcase name="InfoService" time="3.254" classname="com.test.api.testcases.WeatherInfoServiceTests"/>
</testsuite> <!-- com.test.api.testcases.WeatherInfoServiceTests -->
